version: '3'

services:
  mediasoup-server:
    image: 'mediasoup-demo-omni:latest'
    container_name: 'ms-omni'
    hostname: 'ms-omni'
    build:
      dockerfile: ./Dockerfile.all
    environment:
      # - MEDIASOUP_MIN_PORT=40000
      # - MEDIASOUP_MAX_PORT=40010
      - MEDIASOUP_ANNOUNCED_IP
    ports:
      # Media streaming port (UDP).
      - '44444-44449:44444-44449/udp'
      # WebSocket API and signaling (HTTPS).
      - '4443:4443/tcp'
      # iperf3 (testing only).
      - '5201:5201/tcp'
      - '5201:5201/udp'
      # Web application page (HTTPS).
      - '3000-3003:3000-3003/tcp'

  # browser1:
  #   image: 'selenium-browser:latest'
  #   container_name: 'browser1'
  #   hostname: 'browser1'
  #   build:
  #     dockerfile: ./User.dockerfile
  #   depends_on:
  #     - mediasoup-server
  #   networks:
  #     mediasoup-network:
  #       ipv4_address: 10.0.0.12

